### PR TITLE
chore: temporarily remove the config files from .gitignore

### PR DESCRIPTION
**Pull request by katelynsills**
Temporarily remove the config files from .gitignore such that they are always there when expected.

Long-term solution is probably using `await fs.promises.mkdir(defaultsFolder, { recursive: true });` to always make the file, but agoric-sdk master is failing, so I'd like to get this temporary fix in.

### CODE REVIEW

**Review by erights — APPROVED** [review]
Your PR comment describes this as temporary and says what the right long term solution is. Please file an issue on that and add a pointer to that issue from the new "generated" file.

LGTM.

**Review by michaelfig — APPROVED** [review]
LGTM!

**Comment by katelynsills** [comment]
Just waiting on #72 before rerunning CI and merging

**Comment by michaelfig** [comment]
> Just waiting on #72 before rerunning CI and merging

Ready to go!

**Pull request merged**
